### ISSUE TITLE
Print out the total time taken at the end

### ISSUE THREAD

**Issue by keithcodes** [SumoLogic/sumo-report-generator#36]
It would be useful to print out the total time taken so that we can easily record how long it's taking to run similar jobs at different times or with different customers.

**Comment by frankreno** [comment]
You will now see a log line when the sheet is populated, as well as the entire report.

INFO  2016-01-05 03:53:35 ExcelWorksheetPopulator - sheet successfully populated in 00:07

INFO  2016-01-05 03:54:27 ExcelReportGenerator - report successfully generated in 00:14
