### ISSUE TITLE
Create new variable "name" and or allow a way to easily keep track of which job is running

### ISSUE THREAD

**Issue by keithcodes** [SumoLogic/sumo-report-generator#37]
This would allow us to print out the job name when running multiple instances of Sumo Report Gen:

Currently:

INFO  2015-12-01 12:25:04 SumoDataServiceImpl - checking search job status

INFO  2015-12-01 12:25:04 Checking search job status for KeithInc

**Comment by frankreno** [comment]
the sheet name will now be logged when checking the status of a job
